export const categories = [
  "Amazon Devices & Accessories",
  "Amazon Launchpad",
  "Appliances",
  "Apps & Games",
  "Arts, Crafts & Sewing",
  "Audible Books & Originals",
  "Automotive",
  "Baby",
  "Beauty & Personal Care",
  "Books",
  "CDs & Vinyl",
  "Camera & Photo",
  "Cell Phones & Accessories",
  "Clothing, Shoes & Jewelry",
  "Collectible Currencies",
  "Computers & Accessories",
  "Digital Music",
  "Electronics",
  "Entertainment Collectibles",
  "Gift Cards",
  "Grocery & Gourmet Food",
  "Handmade Products",
  "Health & Household",
  "Home & Kitchen",
  "Industrial & Scientific",
  "Kindle Store",
  "Kitchen & Dining",
  "Magazine Subscriptions",
  "Movies & TV",
  "Musical Instruments",
  "Office Products",
  "Patio, Lawn & Garden",
  "Pet Supplies",
  "Prime Pantry",
  "Software",
  "Sports & Outdoors",
  "Sports Collectibles",
  "Tools & Home Improvement",
  "Toys & Games",
  "Video Games"
];
