import React from "react";

import { Card } from "react-bootstrap";
import LAKeyphrasesBody from "./LAKeyphrasesBody";
import LAKeyphrasesHeader from "./LAKeyphrasesHeader";

class LAKeyphrasesCard extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      currentPage: 1
    };

    this.handleNextPageChange = this.handleNextPageChange.bind(this);
    this.handlePrevPageChange = this.handlePrevPageChange.bind(this);
  }

  handleNextPageChange(event) {
    this.setState(state => {
      const maxPage = Math.ceil(this.props.productInfo.keyphrases.length / 5);
      const newPage =
        state.currentPage >= maxPage
          ? state.currentPage
          : state.currentPage + 1;
      return { currentPage: newPage };
    });
  }

  handlePrevPageChange(event) {
    this.setState(state => {
      const newPage =
        state.currentPage <= 1 ? state.currentPage : state.currentPage - 1;
      return { currentPage: newPage };
    });
  }

  render() {
    const perPage = 5;
    let data = [];
    if (this.props.success) {
      data = this.props.productInfo.keyphrases;
    }

    let indexOfLastEl = this.state.currentPage * perPage;
    let indexOfFirstEl = indexOfLastEl - perPage;
    let currentEls = data.slice(indexOfFirstEl, indexOfLastEl);

    const laKeyphrasesToolHelper =
      "Projected keyphrases for the ASIN provided. This is generated by a combination of the product title, product description, and the product features. Note that all keyphrases or keywords are captured using our keyphrase extractor.";

    return (
      <Card className="h-100">
        <LAKeyphrasesHeader
          title={"Product Projected Keyphrases"}
          content={laKeyphrasesToolHelper}
        />
        <LAKeyphrasesBody
          handleNext={this.handleNextPageChange}
          handlePrev={this.handlePrevPageChange}
          bottom={indexOfFirstEl}
          top={indexOfLastEl}
          data={currentEls}
          max={data.length}
        />
      </Card>
    );
  }
}

export default LAKeyphrasesCard;
